name: Build and Run UI App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # 📥 Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 🐳 Build Docker image
      - name: Build Docker Image
        run: docker build -t lite-ui .

      # ▶️ Run container
      - name: Run Container
        run: |
          docker rm -f lite-container || true
          docker run -d -p 3000:3000 --name lite-container lite-ui

      # 🧪 Check running containers
      - name: Verify
        run: docker ps